name = "empowa/nse-housing-onchain"
version = "0.0.1"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'empowa/nse-housing-onchain'"

[repository]
user = "empowa-io"
project = "nse-housing-onchain"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.0.0"
source = "github"

[config.default]
contract_config_marker = "CNF"
contract_order_marker = "ORD"
contract_listing_marker = "LST"
contract_order_min_ada = 2_000_000
contract_bootstrap_utxo_index = 0

[config.default.contract_bootstrap_utxo_hash]
bytes = "94a8c6dd914997d05bc03ec3d550d84ca8b4b9ed965da0f67e31663c"
encoding = "hex"


[config.mainnet]
contract_config_marker = "CNF"
contract_order_marker = "ORD"
contract_listing_marker = "LST"
contract_order_min_ada = 2_000_000
contract_bootstrap_utxo_index = 0

[config.mainnet.contract_bootstrap_utxo_hash]
bytes = "94a8c6dd914997d05bc03ec3d550d84ca8b4b9ed965da0f67e31663c"
encoding = "hex"
